//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kombit.Klassifikation
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stoettesystemerne.dk/klassifikation", ConfigurationName="Kombit.Klassifikation.KlassifikationPortType")]
    public interface KlassifikationPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/klassifikation/klassifikation/opret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Kombit.Klassifikation.opretResponse> opretAsync(Kombit.Klassifikation.opretRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/klassifikation/klassifikation/importer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Kombit.Klassifikation.importerResponse> importerAsync(Kombit.Klassifikation.importerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/klassifikation/klassifikation/passiver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Kombit.Klassifikation.passiverResponse> passiverAsync(Kombit.Klassifikation.passiverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/klassifikation/klassifikation/laes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Kombit.Klassifikation.laesResponse> laesAsync(Kombit.Klassifikation.laesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/klassifikation/klassifikation/ret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Kombit.Klassifikation.retResponse> retAsync(Kombit.Klassifikation.retRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/klassifikation/klassifikation/slet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Kombit.Klassifikation.sletResponse> sletAsync(Kombit.Klassifikation.sletRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/klassifikation/klassifikation/soeg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Kombit.Klassifikation.soegResponse> soegAsync(Kombit.Klassifikation.soegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kombit.dk/sts/klassifikation/klassifikation/list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ListOutputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SoegInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RetInputType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegistreringType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OpretInputType))]
        System.Threading.Tasks.Task<Kombit.Klassifikation.listResponse> listAsync(Kombit.Klassifikation.listRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
    public partial class RequestHeaderType
    {
        
        private string transactionUUIDField;
        
        /// <remarks/>
        public string TransactionUUID
        {
            get
            {
                return this.transactionUUIDField;
            }
            set
            {
                this.transactionUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListOutputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class ListOutputType
    {
        
        private StandardReturType standardReturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnikReturType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class StandardReturType
    {
        
        private string statusKodeField;
        
        private string fejlbeskedTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string StatusKode
        {
            get
            {
                return this.statusKodeField;
            }
            set
            {
                this.statusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FejlbeskedTekst
        {
            get
            {
                return this.fejlbeskedTekstField;
            }
            set
            {
                this.fejlbeskedTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UnikReturType : StandardReturType
    {
        
        private string typeField;
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ListOutputType", Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class ListOutputType1 : ListOutputType
    {
        
        private FiltreretOejebliksbilledeType[] filtreretOejebliksbilledeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FiltreretOejebliksbillede", Order=0)]
        public FiltreretOejebliksbilledeType[] FiltreretOejebliksbillede
        {
            get
            {
                return this.filtreretOejebliksbilledeField;
            }
            set
            {
                this.filtreretOejebliksbilledeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class FiltreretOejebliksbilledeType
    {
        
        private SagDokObjektType objektIDField;
        
        private DataEjer dataEjerField;
        
        private RegistreringType1[] registreringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SagDokObjektType ObjektID
        {
            get
            {
                return this.objektIDField;
            }
            set
            {
                this.objektIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DataEjer DataEjer
        {
            get
            {
                return this.dataEjerField;
            }
            set
            {
                this.dataEjerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering", Order=2)]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KlassifikationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesFiltreretOutputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SagDokObjektType
    {
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class KlassifikationType : SagDokObjektType
    {
        
        private RegistreringType1[] registreringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Registrering", Order=0)]
        public RegistreringType1[] Registrering
        {
            get
            {
                return this.registreringField;
            }
            set
            {
                this.registreringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RegistreringType", Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class RegistreringType1 : RegistreringType
    {
        
        private EgenskabType[] attributListeField;
        
        private PubliceretStatusType[] tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PubliceretStatus", IsNullable=false)]
        public PubliceretStatusType[] TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class EgenskabType
    {
        
        private VirkningType virkningField;
        
        private string brugervendtNoegleTekstField;
        
        private string titelTekstField;
        
        private string beskrivelseTekstField;
        
        private string kaldenavnTekstField;
        
        private string ophavsretTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=0)]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=1)]
        public string BrugervendtNoegleTekst
        {
            get
            {
                return this.brugervendtNoegleTekstField;
            }
            set
            {
                this.brugervendtNoegleTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=2)]
        public string TitelTekst
        {
            get
            {
                return this.titelTekstField;
            }
            set
            {
                this.titelTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=3)]
        public string BeskrivelseTekst
        {
            get
            {
                return this.beskrivelseTekstField;
            }
            set
            {
                this.beskrivelseTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=4)]
        public string KaldenavnTekst
        {
            get
            {
                return this.kaldenavnTekstField;
            }
            set
            {
                this.kaldenavnTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=5)]
        public string OphavsretTekst
        {
            get
            {
                return this.ophavsretTekstField;
            }
            set
            {
                this.ophavsretTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class VirkningType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private UnikIdType aktoerRefField;
        
        private AktoerTypeKodeType aktoerTypeKodeField;
        
        private bool aktoerTypeKodeFieldSpecified;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class TidspunktType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GraenseIndikator", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TidsstempelDatoTid", typeof(System.DateTime), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UuidLabelInputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UnikIdType
    {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URNIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        URNIdentifikator,
        
        /// <remarks/>
        UUIDIdentifikator,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UuidLabelInputType : UnikIdType
    {
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public enum AktoerTypeKodeType
    {
        
        /// <remarks/>
        Organisation,
        
        /// <remarks/>
        OrganisationEnhed,
        
        /// <remarks/>
        OrganisationFunktion,
        
        /// <remarks/>
        Bruger,
        
        /// <remarks/>
        ItSystem,
        
        /// <remarks/>
        Interessefaellesskab,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class PubliceretStatusType
    {
        
        private VirkningType virkningField;
        
        private bool erPubliceretIndikatorField;
        
        private bool erPubliceretIndikatorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=0)]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=1)]
        public bool ErPubliceretIndikator
        {
            get
            {
                return this.erPubliceretIndikatorField;
            }
            set
            {
                this.erPubliceretIndikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErPubliceretIndikatorSpecified
        {
            get
            {
                return this.erPubliceretIndikatorFieldSpecified;
            }
            set
            {
                this.erPubliceretIndikatorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class RelationListeType
    {
        
        private AktoerRelationType ansvarligField;
        
        private AktoerRelationType ejerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=0)]
        public AktoerRelationType Ansvarlig
        {
            get
            {
                return this.ansvarligField;
            }
            set
            {
                this.ansvarligField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oio:sagdok:3.0.0", Order=1)]
        public AktoerRelationType Ejer
        {
            get
            {
                return this.ejerField;
            }
            set
            {
                this.ejerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class AktoerRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KlassifikationRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacetRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DokumentRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SagRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArkivRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AktoerRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VirksomhedRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganisationEnhedRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MyndighedRelationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KlasseRelationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RelationType
    {
        
        private VirkningType virkningField;
        
        private UuidLabelInputType referenceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VirkningType Virkning
        {
            get
            {
                return this.virkningField;
            }
            set
            {
                this.virkningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UuidLabelInputType ReferenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class KlassifikationRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class FacetRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class DokumentRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SagRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class ArkivRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OrganisationRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class VirksomhedRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OrganisationEnhedRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class MyndighedRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class KlasseRelationType : RelationType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistreringType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RegistreringType
    {
        
        private string noteTekstField;
        
        private System.DateTime tidspunktField;
        
        private bool tidspunktFieldSpecified;
        
        private LivscyklusKodeType livscyklusKodeField;
        
        private bool livscyklusKodeFieldSpecified;
        
        private UnikIdType brugerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Tidspunkt
        {
            get
            {
                return this.tidspunktField;
            }
            set
            {
                this.tidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TidspunktSpecified
        {
            get
            {
                return this.tidspunktFieldSpecified;
            }
            set
            {
                this.tidspunktFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public enum LivscyklusKodeType
    {
        
        /// <remarks/>
        Opstaaet,
        
        /// <remarks/>
        Importeret,
        
        /// <remarks/>
        Passiveret,
        
        /// <remarks/>
        Slettet,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class LaesFiltreretOutputType : SagDokObjektType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class DataEjer
    {
        
        private string cVRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CVR
        {
            get
            {
                return this.cVRField;
            }
            set
            {
                this.cVRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class ListInputType
    {
        
        private string[] uUIDIdentifikatorField;
        
        private TidspunktType virkningFraFilterField;
        
        private TidspunktType virkningTilFilterField;
        
        private TidspunktType registreringFraFilterField;
        
        private TidspunktType registreringTilFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUIDIdentifikator", Order=0)]
        public string[] UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegOutputType
    {
        
        private StandardReturType standardReturField;
        
        private string[] idListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UUIDIdentifikator", IsNullable=false)]
        public string[] IdListe
        {
            get
            {
                return this.idListeField;
            }
            set
            {
                this.idListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegVirkningType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private UnikIdType aktoerRefField;
        
        private AktoerTypeKodeType aktoerTypeKodeField;
        
        private bool aktoerTypeKodeFieldSpecified;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UnikIdType AktoerRef
        {
            get
            {
                return this.aktoerRefField;
            }
            set
            {
                this.aktoerRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AktoerTypeKodeType AktoerTypeKode
        {
            get
            {
                return this.aktoerTypeKodeField;
            }
            set
            {
                this.aktoerTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AktoerTypeKodeSpecified
        {
            get
            {
                return this.aktoerTypeKodeFieldSpecified;
            }
            set
            {
                this.aktoerTypeKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegRegistreringType
    {
        
        private TidspunktType fraTidspunktField;
        
        private TidspunktType tilTidspunktField;
        
        private LivscyklusKodeType livscyklusKodeField;
        
        private bool livscyklusKodeFieldSpecified;
        
        private UnikIdType brugerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TidspunktType FraTidspunkt
        {
            get
            {
                return this.fraTidspunktField;
            }
            set
            {
                this.fraTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType TilTidspunkt
        {
            get
            {
                return this.tilTidspunktField;
            }
            set
            {
                this.tilTidspunktField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LivscyklusKodeType LivscyklusKode
        {
            get
            {
                return this.livscyklusKodeField;
            }
            set
            {
                this.livscyklusKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivscyklusKodeSpecified
        {
            get
            {
                return this.livscyklusKodeFieldSpecified;
            }
            set
            {
                this.livscyklusKodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UnikIdType BrugerRef
        {
            get
            {
                return this.brugerRefField;
            }
            set
            {
                this.brugerRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SoegInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class SoegInputType
    {
        
        private string foersteResultatReferenceField;
        
        private string maksimalAntalKvantitetField;
        
        private SoegRegistreringType soegRegistreringField;
        
        private SoegVirkningType soegVirkningField;
        
        private DataEjer dataEjerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string FoersteResultatReference
        {
            get
            {
                return this.foersteResultatReferenceField;
            }
            set
            {
                this.foersteResultatReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string MaksimalAntalKvantitet
        {
            get
            {
                return this.maksimalAntalKvantitetField;
            }
            set
            {
                this.maksimalAntalKvantitetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SoegRegistreringType SoegRegistrering
        {
            get
            {
                return this.soegRegistreringField;
            }
            set
            {
                this.soegRegistreringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SoegVirkningType SoegVirkning
        {
            get
            {
                return this.soegVirkningField;
            }
            set
            {
                this.soegVirkningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DataEjer DataEjer
        {
            get
            {
                return this.dataEjerField;
            }
            set
            {
                this.dataEjerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoegInputType", Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class SoegInputType1 : SoegInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private PubliceretStatusType[] tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PubliceretStatus", IsNullable=false)]
        public PubliceretStatusType[] TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class RetInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RetInputType", Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class RetInputType1 : RetInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private PubliceretStatusType[] tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PubliceretStatus", IsNullable=false)]
        public PubliceretStatusType[] TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class LaesInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private TidspunktType virkningFraFilterField;
        
        private TidspunktType virkningTilFilterField;
        
        private TidspunktType registreringFraFilterField;
        
        private TidspunktType registreringTilFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TidspunktType VirkningFraFilter
        {
            get
            {
                return this.virkningFraFilterField;
            }
            set
            {
                this.virkningFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TidspunktType VirkningTilFilter
        {
            get
            {
                return this.virkningTilFilterField;
            }
            set
            {
                this.virkningTilFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TidspunktType RegistreringFraFilter
        {
            get
            {
                return this.registreringFraFilterField;
            }
            set
            {
                this.registreringFraFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TidspunktType RegistreringTilFilter
        {
            get
            {
                return this.registreringTilFilterField;
            }
            set
            {
                this.registreringTilFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class UuidNoteInputType
    {
        
        private string uUIDIdentifikatorField;
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class ImportInputType
    {
        
        private KlassifikationType klassifikationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KlassifikationType Klassifikation
        {
            get
            {
                return this.klassifikationField;
            }
            set
            {
                this.klassifikationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpretOutputType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LaesOutputType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class BasicOutputType
    {
        
        private StandardReturType standardReturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StandardReturType StandardRetur
        {
            get
            {
                return this.standardReturField;
            }
            set
            {
                this.standardReturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OpretOutputType : BasicOutputType
    {
        
        private string uUIDIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUIDIdentifikator
        {
            get
            {
                return this.uUIDIdentifikatorField;
            }
            set
            {
                this.uUIDIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class LaesOutputType : BasicOutputType
    {
        
        private FiltreretOejebliksbilledeType filtreretOejebliksbilledeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FiltreretOejebliksbilledeType FiltreretOejebliksbillede
        {
            get
            {
                return this.filtreretOejebliksbilledeField;
            }
            set
            {
                this.filtreretOejebliksbilledeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpretInputType1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oio:sagdok:3.0.0")]
    public partial class OpretInputType
    {
        
        private string noteTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NoteTekst
        {
            get
            {
                return this.noteTekstField;
            }
            set
            {
                this.noteTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OpretInputType", Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/")]
    public partial class OpretInputType1 : OpretInputType
    {
        
        private EgenskabType[] attributListeField;
        
        private PubliceretStatusType[] tilstandListeField;
        
        private RelationListeType relationListeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Egenskab", IsNullable=false)]
        public EgenskabType[] AttributListe
        {
            get
            {
                return this.attributListeField;
            }
            set
            {
                this.attributListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PubliceretStatus", IsNullable=false)]
        public PubliceretStatusType[] TilstandListe
        {
            get
            {
                return this.tilstandListeField;
            }
            set
            {
                this.tilstandListeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RelationListeType RelationListe
        {
            get
            {
                return this.relationListeField;
            }
            set
            {
                this.relationListeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opretRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.OpretInputType1 OpretInput;
        
        public opretRequest()
        {
        }
        
        public opretRequest(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.OpretInputType1 OpretInput)
        {
            this.RequestHeader = RequestHeader;
            this.OpretInput = OpretInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opretResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.OpretOutputType OpretOutput;
        
        public opretResponse()
        {
        }
        
        public opretResponse(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.OpretOutputType OpretOutput)
        {
            this.RequestHeader = RequestHeader;
            this.OpretOutput = OpretOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importerRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.ImportInputType ImportInput;
        
        public importerRequest()
        {
        }
        
        public importerRequest(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.ImportInputType ImportInput)
        {
            this.RequestHeader = RequestHeader;
            this.ImportInput = ImportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importerResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.BasicOutputType ImportOutput;
        
        public importerResponse()
        {
        }
        
        public importerResponse(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.BasicOutputType ImportOutput)
        {
            this.RequestHeader = RequestHeader;
            this.ImportOutput = ImportOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class passiverRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.UuidNoteInputType PassiverInput;
        
        public passiverRequest()
        {
        }
        
        public passiverRequest(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.UuidNoteInputType PassiverInput)
        {
            this.RequestHeader = RequestHeader;
            this.PassiverInput = PassiverInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class passiverResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.BasicOutputType PassiverOutput;
        
        public passiverResponse()
        {
        }
        
        public passiverResponse(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.BasicOutputType PassiverOutput)
        {
            this.RequestHeader = RequestHeader;
            this.PassiverOutput = PassiverOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laesRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.LaesInputType LaesInput;
        
        public laesRequest()
        {
        }
        
        public laesRequest(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.LaesInputType LaesInput)
        {
            this.RequestHeader = RequestHeader;
            this.LaesInput = LaesInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class laesResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.LaesOutputType LaesOutput;
        
        public laesResponse()
        {
        }
        
        public laesResponse(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.LaesOutputType LaesOutput)
        {
            this.RequestHeader = RequestHeader;
            this.LaesOutput = LaesOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.RetInputType1 RetInput;
        
        public retRequest()
        {
        }
        
        public retRequest(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.RetInputType1 RetInput)
        {
            this.RequestHeader = RequestHeader;
            this.RetInput = RetInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.BasicOutputType RetOutput;
        
        public retResponse()
        {
        }
        
        public retResponse(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.BasicOutputType RetOutput)
        {
            this.RequestHeader = RequestHeader;
            this.RetOutput = RetOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sletRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.UuidNoteInputType SletInput;
        
        public sletRequest()
        {
        }
        
        public sletRequest(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.UuidNoteInputType SletInput)
        {
            this.RequestHeader = RequestHeader;
            this.SletInput = SletInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sletResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.BasicOutputType SletOutput;
        
        public sletResponse()
        {
        }
        
        public sletResponse(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.BasicOutputType SletOutput)
        {
            this.RequestHeader = RequestHeader;
            this.SletOutput = SletOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class soegRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.SoegInputType1 SoegInput;
        
        public soegRequest()
        {
        }
        
        public soegRequest(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.SoegInputType1 SoegInput)
        {
            this.RequestHeader = RequestHeader;
            this.SoegInput = SoegInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class soegResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.SoegOutputType SoegOutput;
        
        public soegResponse()
        {
        }
        
        public soegResponse(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.SoegOutputType SoegOutput)
        {
            this.RequestHeader = RequestHeader;
            this.SoegOutput = SoegOutput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.ListInputType ListInput;
        
        public listRequest()
        {
        }
        
        public listRequest(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.ListInputType ListInput)
        {
            this.RequestHeader = RequestHeader;
            this.ListInput = ListInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://kombit.dk/xml/schemas/RequestHeader/1/")]
        public Kombit.Klassifikation.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stoettesystemerne.dk/klassifikation/klassifikation/7/", Order=0)]
        public Kombit.Klassifikation.ListOutputType1 ListOutput;
        
        public listResponse()
        {
        }
        
        public listResponse(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.ListOutputType1 ListOutput)
        {
            this.RequestHeader = RequestHeader;
            this.ListOutput = ListOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface KlassifikationPortTypeChannel : Kombit.Klassifikation.KlassifikationPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class KlassifikationPortTypeClient : System.ServiceModel.ClientBase<Kombit.Klassifikation.KlassifikationPortType>, Kombit.Klassifikation.KlassifikationPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KlassifikationPortTypeClient() : 
                base(KlassifikationPortTypeClient.GetDefaultBinding(), KlassifikationPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Klassifikation.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KlassifikationPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(KlassifikationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), KlassifikationPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KlassifikationPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KlassifikationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KlassifikationPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KlassifikationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KlassifikationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.Klassifikation.opretResponse> Kombit.Klassifikation.KlassifikationPortType.opretAsync(Kombit.Klassifikation.opretRequest request)
        {
            return base.Channel.opretAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.Klassifikation.opretResponse> opretAsync(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.OpretInputType1 OpretInput)
        {
            Kombit.Klassifikation.opretRequest inValue = new Kombit.Klassifikation.opretRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.OpretInput = OpretInput;
            return ((Kombit.Klassifikation.KlassifikationPortType)(this)).opretAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.Klassifikation.importerResponse> Kombit.Klassifikation.KlassifikationPortType.importerAsync(Kombit.Klassifikation.importerRequest request)
        {
            return base.Channel.importerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.Klassifikation.importerResponse> importerAsync(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.ImportInputType ImportInput)
        {
            Kombit.Klassifikation.importerRequest inValue = new Kombit.Klassifikation.importerRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ImportInput = ImportInput;
            return ((Kombit.Klassifikation.KlassifikationPortType)(this)).importerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.Klassifikation.passiverResponse> Kombit.Klassifikation.KlassifikationPortType.passiverAsync(Kombit.Klassifikation.passiverRequest request)
        {
            return base.Channel.passiverAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.Klassifikation.passiverResponse> passiverAsync(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.UuidNoteInputType PassiverInput)
        {
            Kombit.Klassifikation.passiverRequest inValue = new Kombit.Klassifikation.passiverRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.PassiverInput = PassiverInput;
            return ((Kombit.Klassifikation.KlassifikationPortType)(this)).passiverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.Klassifikation.laesResponse> Kombit.Klassifikation.KlassifikationPortType.laesAsync(Kombit.Klassifikation.laesRequest request)
        {
            return base.Channel.laesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.Klassifikation.laesResponse> laesAsync(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.LaesInputType LaesInput)
        {
            Kombit.Klassifikation.laesRequest inValue = new Kombit.Klassifikation.laesRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.LaesInput = LaesInput;
            return ((Kombit.Klassifikation.KlassifikationPortType)(this)).laesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.Klassifikation.retResponse> Kombit.Klassifikation.KlassifikationPortType.retAsync(Kombit.Klassifikation.retRequest request)
        {
            return base.Channel.retAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.Klassifikation.retResponse> retAsync(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.RetInputType1 RetInput)
        {
            Kombit.Klassifikation.retRequest inValue = new Kombit.Klassifikation.retRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.RetInput = RetInput;
            return ((Kombit.Klassifikation.KlassifikationPortType)(this)).retAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.Klassifikation.sletResponse> Kombit.Klassifikation.KlassifikationPortType.sletAsync(Kombit.Klassifikation.sletRequest request)
        {
            return base.Channel.sletAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.Klassifikation.sletResponse> sletAsync(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.UuidNoteInputType SletInput)
        {
            Kombit.Klassifikation.sletRequest inValue = new Kombit.Klassifikation.sletRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SletInput = SletInput;
            return ((Kombit.Klassifikation.KlassifikationPortType)(this)).sletAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.Klassifikation.soegResponse> Kombit.Klassifikation.KlassifikationPortType.soegAsync(Kombit.Klassifikation.soegRequest request)
        {
            return base.Channel.soegAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.Klassifikation.soegResponse> soegAsync(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.SoegInputType1 SoegInput)
        {
            Kombit.Klassifikation.soegRequest inValue = new Kombit.Klassifikation.soegRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.SoegInput = SoegInput;
            return ((Kombit.Klassifikation.KlassifikationPortType)(this)).soegAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kombit.Klassifikation.listResponse> Kombit.Klassifikation.KlassifikationPortType.listAsync(Kombit.Klassifikation.listRequest request)
        {
            return base.Channel.listAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kombit.Klassifikation.listResponse> listAsync(Kombit.Klassifikation.RequestHeaderType RequestHeader, Kombit.Klassifikation.ListInputType ListInput)
        {
            Kombit.Klassifikation.listRequest inValue = new Kombit.Klassifikation.listRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.ListInput = ListInput;
            return ((Kombit.Klassifikation.KlassifikationPortType)(this)).listAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Klassifikation))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Klassifikation))
            {
                return new System.ServiceModel.EndpointAddress("https://klassifikation.stoettesystemerne.dk/klassifikation/7");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KlassifikationPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.Klassifikation);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KlassifikationPortTypeClient.GetEndpointAddress(EndpointConfiguration.Klassifikation);
        }
        
        public enum EndpointConfiguration
        {
            
            Klassifikation,
        }
    }
}
